# Imagen base de Node con Angular CLI
FROM node:22.13.1

# Crear carpeta de trabajo dentro del contenedor
WORKDIR /app

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli@19.0.4

# Copiar los archivos de dependencias
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto donde Angular sirve la app
EXPOSE 4200

# Comando por defecto: iniciar servidor Angular
CMD ["ng", "serve", "--host", "0.0.0.0"]
