
services:
  angular:
    container_name: angular-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ng serve --host 0.0.0.0 --poll=1000
